ci: update

diff --git a/.github/workflows/make-release-at-jira.yml b/.github/workflows/make-release-at-jira.yml
--- a/.github/workflows/make-release-at-jira.yml
+++ b/.github/workflows/make-release-at-jira.yml
@@ -22,13 +22,80 @@ jobs:
       - name: Get branch name and extract Jira issue ID
         id: extract_issue_id
         run: |
-          echo "Branch name: ${GITHUB_HEAD_REF}"
-          ISSUE_ID=$(echo "${GITHUB_HEAD_REF}" | grep -oE '[A-Z]+-[0-9]+')
+          BRANCH_NAME="${{ github.base_ref || github.ref_name }}
+          echo "Branch: $BRANCH_NAME"
+          echo "branch=${BRANCH_NAME}" >> $GITHUB_ENV
+          ISSUE_ID=$(echo "$BRANCH_NAME" | grep -oE '[A-Z]+-[0-9]+')
           echo "Issue ID: ${ISSUE_ID}"
           echo "jira_issue_id=${ISSUE_ID}" >> $GITHUB_ENV
 
+      - name: Create Jira component
+        id: creat_jira_component
+        run: |
+          PROJECT=$(echo "${env.branch}" | grep -oE '[A-Z]+')
+          
+          echo "Create Jira component ${{ env.APP_NAME }}. Project ${PROJECT}"
+          
+          CREATE_COMPONENT=$(cat <<EOF
+          {
+            "description": "Component ${{ env.APP_NAME }} created automatically",
+            "name": "${{ env.APP_NAME }}",
+            "project": "$PROJECT",
+            "assigneeType": "PROJECT_LEAD"
+          }
+          EOF
+          )
+
+          echo "${CREATE_COMPONENT}"
+          
+          curl --silent \
+            --request POST \
+            --url "https://trend-it.atlassian.net/rest/api/3/component" \
+            --header "Authorization: Basic ${{ secrets.JIRA_API_KEY }}" \
+            --header "Content-Type: application/json" \
+            --data "$CREATE_COMPONENT"
+          
+          echo "\nComponent: ${{ env.APP_NAME }}"
+          echo "jira_component=${{ env.APP_NAME }}" >> $GITHUB_ENV
+
+      - name: Update Jira issue with Component
+        id: update_jira
+        if: github.event.pull_request.merged != true
+        run: |
+          echo "Updating Jira issue ${{ env.jira_issue_id }} set component: ${{ env.APP_NAME }}"
+
+          SET_COMPONENT_JSON=$(cat <<EOF
+          {
+            "update": {
+              "components": [
+                {
+                  "add": {
+                    "name": "${{ env.jira_component }}"
+                  }
+                }
+              ]
+            }
+          }
+          EOF
+          )
+
+          HTTP_CODE=$(curl --silent --output /dev/null --write-out "%{http_code}" \
+          --request PUT \
+          --url "https://trend-it.atlassian.net/rest/api/3/issue/${{ env.jira_issue_id }}" \
+          --header "Authorization: Basic ${{ secrets.JIRA_API_KEY }}" \
+          --header "Content-Type: application/json" \
+          --data "$SET_COMPONENT_JSON")
+          
+          if [[ "$HTTP_CODE" -ge 200 && "$HTTP_CODE" -lt 300 ]]; then
+            echo  "Jira issue updated successfully with HTTP code $HTTP_CODE"
+          else
+            echo "Failed to update Jira issue. HTTP code: $HTTP_CODE"
+            exit 1
+          fi
+
       - name: Create Jira release
         id: creat_jira_release
+        if: github.event.pull_request.merged == true
         run: |
           PROJECT=$(echo "${GITHUB_HEAD_REF}" | grep -oE '[A-Z]+')
           
@@ -58,6 +125,7 @@ jobs:
 
       - name: Update Jira issue with Fix Versions
         id: update_jira
+        if: github.event.pull_request.merged == true
         run: |
           echo "Updating Jira issue ${{ env.jira_issue_id }} with Fix Version ${{ env.APP_NAME }}-${{ env.APP_VERSION }}"
 
