ci: initial jira front version

diff --git a/.github/workflows/set-version-front-to-jira-at-release.yml b/.github/workflows/set-version-front-to-jira-at-release.yml
--- a/.github/workflows/set-version-front-to-jira-at-release.yml
+++ b/.github/workflows/set-version-front-to-jira-at-release.yml
@@ -23,14 +23,14 @@ jobs:
         id: extract_issue_id
         run: |
           echo "Branch name: ${GITHUB_HEAD_REF}"
-          ISSUE_ID=$(echo "${GITHUB_HEAD_REF}" | grep -oE '[A-Z]+-[0-9]+')
+          ISSUE_ID=$(echo "${GITHUB_HEAD_REF}" | grep -oE '[a-z]+-[0-9]+')
           echo "Issue ID: ${ISSUE_ID}"
           echo "jira_issue_id=${ISSUE_ID}" >> $GITHUB_ENV
 
       - name: Create Jira release
         id: creat_jira_release
         run: |
-          PROJECT=$(echo "${GITHUB_HEAD_REF}" | grep -oE '[A-Z]+')
+          PROJECT=$(echo "${GITHUB_HEAD_REF}" | cut -f2 -d '/' | grep -oE '[a-z]+')
           
           echo "Create Jira release ${{ env.APP_NAME }}-${{ env.APP_VERSION }}. Project ${PROJECT}"
           
@@ -86,46 +86,46 @@ jobs:
           echo "\nComponent: ${{ env.APP_NAME }}"
           echo "jira_component=${{ env.APP_NAME }}" >> $GITHUB_ENV
 
-#      - name: Update Jira issue with Fix Versions
-#        id: update_jira
-#        run: |
-#          echo "Updating Jira issue ${{ env.jira_issue_id }} with Fix Version ${{ env.APP_NAME }}-${{ env.APP_VERSION }}"
-#
-#          FIX_VERSION_JSON=$(cat <<EOF
-#          {
-#            "update": {
-#              "fixVersions": [
-#                {
-#                  "add": {
-#                    "name": "${{ env.jira_version }}"
-#                  }
-#                }
-#              ],
-#              "components": [
-#                {
-#                  "add": {
-#                    "name": "${{ env.jira_component }}"
-#                  }
-#                }
-#              ]
-#            }
-#          }
-#          EOF
-#          )
-#
-#          HTTP_CODE=$(curl --silent --output /dev/null --write-out "%{http_code}" \
-#          --request PUT \
-#          --url "https://trend-it.atlassian.net/rest/api/3/issue/${{ env.jira_issue_id }}" \
-#          --header "Authorization: Basic ${{ secrets.JIRA_API_KEY }}" \
-#          --header "Content-Type: application/json" \
-#          --data "$FIX_VERSION_JSON")
-#
-#          if [[ "$HTTP_CODE" -ge 200 && "$HTTP_CODE" -lt 300 ]]; then
-#            echo  "Jira issue updated successfully with HTTP code $HTTP_CODE"
-#          else
-#            echo "Failed to update Jira issue. HTTP code: $HTTP_CODE"
-#            exit 1
-#          fi
+      - name: Update Jira issue with Fix Versions
+        id: update_jira
+        run: |
+          echo "Updating Jira issue ${{ env.jira_issue_id }} with Fix Version ${{ env.APP_NAME }}-${{ env.APP_VERSION }}"
+
+          FIX_VERSION_JSON=$(cat <<EOF
+          {
+            "update": {
+              "fixVersions": [
+                {
+                  "add": {
+                    "name": "${{ env.jira_version }}"
+                  }
+                }
+              ],
+              "components": [
+                {
+                  "add": {
+                    "name": "${{ env.jira_component }}"
+                  }
+                }
+              ]
+            }
+          }
+          EOF
+          )
+
+          HTTP_CODE=$(curl --silent --output /dev/null --write-out "%{http_code}" \
+          --request PUT \
+          --url "https://trend-it.atlassian.net/rest/api/3/issue/${{ env.jira_issue_id }}" \
+          --header "Authorization: Basic ${{ secrets.JIRA_API_KEY }}" \
+          --header "Content-Type: application/json" \
+          --data "$FIX_VERSION_JSON")
+
+          if [[ "$HTTP_CODE" -ge 200 && "$HTTP_CODE" -lt 300 ]]; then
+            echo  "Jira issue updated successfully with HTTP code $HTTP_CODE"
+          else
+            echo "Failed to update Jira issue. HTTP code: $HTTP_CODE"
+            exit 1
+          fi
 
     env:
       APP_VERSION: ${{ inputs.APP_VERSION }}
